spring:
  application:
    name: Journal App
  datasource:
    url: jdbc:postgresql://localhost:5433/journalApp
    username: postgres
    password: QWERTY@123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb+srv://kutkarshh:hello@mycluster.9v9fvud.mongodb.net/?retryWrites=true&w=majority&appName=myCluster
      database: journalApp